### Algumas ideias:

**Cenário de problema: Operadora de internet/telefone quer reduzir cancelamentos.**

1. Objetivo:
**Prever cancelamento**.

Como a empresa pode agir antes:
*   Oferecer descontos
*   Melhorar atendimento
*   Criar campanhas de retenção
*   Item da lista

Exemplo de pergunta:
*   Qual perfil mais cancela?
*   Quanto a empresa perde?
*   Quais serviços ajudam na retenção?
*   Contrato mensal aumenta churn?
*   Qual faixa de valor tem maior evasão?

#Importações

In [41]:
#Importações
import pandas as pd
import sqlite3

#Análise

In [42]:
#Conexão com o repositório do github
!git clone https://github.com/joyexplorer/hackathon-elas-tech-grupo7.git

fatal: destination path 'hackathon-elas-tech-grupo7' already exists and is not an empty directory.

In [43]:
df = pd.read_csv('/content/hackathon-elas-tech-grupo7/dados/brutos/telco-customer-churn.csv')

In [44]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [45]:
#Quantidade de linhas e colunas dos nossos dados
df.shape

(7043, 21)

In [46]:
#São 21 colunas:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [48]:
#Opção de renomear as colunas para português / Só se acharem necessário
#TotalCharges está como objeto e deveria ser numérico
#Talvez não precisamos de todas as colunas

'''df.rename(columns={
    'customerID': 'id_cliente',
    'gender': 'genero',
    'SeniorCitizen': 'idoso',
    'Partner': 'possui_parceiro',
    'Dependents': 'possui_dependentes',
    'tenure': 'tempo_contrato_meses',
    'PhoneService': 'servico_telefone',
    'MultipleLines': 'multiplas_linhas',
    'InternetService': 'servico_internet',
    'OnlineSecurity': 'seguranca_online',
    'OnlineBackup': 'backup_online',
    'DeviceProtection': 'protecao_dispositivo',
    'TechSupport': 'suporte_tecnico',
    'StreamingTV': 'streaming_tv',
    'StreamingMovies': 'streaming_filmes',
    'Contract': 'tipo_contrato',
    'PaperlessBilling': 'fatura_digital',
    'PaymentMethod': 'metodo_pagamento',
    'MonthlyCharges': 'valor_mensal',
    'TotalCharges': 'valor_total',
    'Churn': 'cancelamento'
}, inplace=True) '''

"df.rename(columns={\n    'customerID': 'id_cliente',\n    'gender': 'genero',\n    'SeniorCitizen': 'idoso',\n    'Partner': 'possui_parceiro',\n    'Dependents': 'possui_dependentes',\n    'tenure': 'tempo_contrato_meses',\n    'PhoneService': 'servico_telefone',\n    'MultipleLines': 'multiplas_linhas',\n    'InternetService': 'servico_internet',\n    'OnlineSecurity': 'seguranca_online',\n    'OnlineBackup': 'backup_online',\n    'DeviceProtection': 'protecao_dispositivo',\n    'TechSupport': 'suporte_tecnico',\n    'StreamingTV': 'streaming_tv',\n    'StreamingMovies': 'streaming_filmes',\n    'Contract': 'tipo_contrato',\n    'PaperlessBilling': 'fatura_digital',\n    'PaymentMethod': 'metodo_pagamento',\n    'MonthlyCharges': 'valor_mensal',\n    'TotalCharges': 'valor_total',\n    'Churn': 'cancelamento'\n}, inplace=True) "

#SQL

In [49]:
#Antes estava conectando ao drive
'''conn = sqlite3.connect('/content/drive/MyDrive/Documentos/hackathon_elastech_telcochurn.db') '''

"conn = sqlite3.connect('/content/drive/MyDrive/Documentos/hackathon_elastech_telcochurn.db') "

In [50]:
query = "SELECT * FROM clientes LIMIT 5;"
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes